### ISSUE TITLE
Update readme with next release?

### ISSUE THREAD

**Issue by webremote** [mikemadisonweb/yii2-rabbitmq#1]
hey mike,

if you could update the readme with configuration example and implementation example, that would be very helpful!

**Comment by mikemadisonweb** [comment]
Hi Chris, 
Thanks for your feedback, i had updated README file with configuration and usage examples. Feel free to contact me if you will have troubles with it/

**Comment by webremote** [comment]
hi mike, thanks for the examples! it really is a good plugin! 👍
