### ISSUE TITLE
multipleConsumers doesn't use queue_options

### ISSUE THREAD

**Issue by michaelarnauts** [mikemadisonweb/yii2-rabbitmq#21]
When initializing a multipleConsumer, it doesn't read the `queue_options` configuration.

**Comment by mikemadisonweb** [comment]
Hi Michael,
Yes, it doesn't, but multiple consumer is a console command that is consuming messages from multiple queues and each of them can have different options. That is why multipleConsumer has a `queues` array, each element of that array may have the same parameters as in queue_options of an ordinary consumer.
It sounds confusing, I will try to change that in a future major release. As for now, I have added some clarifications in a README file.
