### ISSUE TITLE
additionalProperties is dropped from Producer::publish()

### ISSUE THREAD

**Issue by michaelarnauts** [mikemadisonweb/yii2-rabbitmq#23]
Any reason why `$additionalProperties` is dropped from `Producer::publish()` in v2.0? This could be useful to support the `priority` flag you can set on a message.

I would also need a way to define `x-max-priority` on the queue, but that also seemed missing in the previous version.

**Comment by mikemadisonweb** [comment]
Hello Michael,
Yep, that's my mistake. I will put that in a patch release.
As for the x-max-priority, it's a queue option, so you can define it in the `arguments` option of the queue configuration. You can find more info on how to set it [here](https://github.com/php-amqplib/php-amqplib/issues/268).
