### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by erikverheij** [mikemadisonweb/yii2-rabbitmq#3]
Hi Mikhail , could you make a new release? Then I can use your repo instead of my own fork in our project. Thank you in advance!

**Comment by mikemadisonweb** [comment]
Hi Erik. Sure, made it. Also if you have some suggestions about new functionality feel free to share ideas.

**Comment by erikverheij** [comment]
Thank you! There is quite some activity in the [php-amqplib/RabbitMqBundle](https://github.com/php-amqplib/RabbitMqBundle/commits/master) repo. I think we might get inspired by fixes and new functionallity they add in that repo. Whenever we need some functionallity or a fix that has already been implemented in that repo we will definitely make a PR for it :)
