### ISSUE TITLE
README fix

### ISSUE THREAD

**Issue by gyr9i** [mikemadisonweb/yii2-rabbitmq#34]
RAEDME "Logger" section configuration example is invalid. According to code in example
logger configuration contains key `'enable' => true`.
But it generates exception 'mikemadisonweb\rabbitmq\exceptions\InvalidConfigException' with message 'Unknown options: {"enable":true}'
Please fix documentation, because the key responsible for enabling is `'log' => true`.
And also by default it disabled. But in docs has written another

**Comment by mikemadisonweb** [comment]
Thank you for your contribution, I have updated the README file.
