### ISSUE TITLE
Yii::info('logging message') not working within consumer execute

### ISSUE THREAD

**Issue by gvanto** [mikemadisonweb/yii2-rabbitmq#36]
I've noticed that the usual console logging I do using Yii::info() doesn't work when called within my consumer's execute method.

The console method which **publishes** the rabbitmq message calls Yii::info('Publishing msg ...') and it gets logged correctly (in both app.log and the db log table where I configured it to go to), but the execute method in the consumer does not. I noticed that when the consumer is killed, the messages DO finally get written but this is not ideal as the consumer is supposed to run continuously and never die so log messages will never get written.

For error logging purposes it would be good if Yii::info / Yii::error() worked in the consumer (in realtime as for other console scripts), is there a way of achieving this?

Btw thanks for a great yii2 extension

**Comment by mikemadisonweb** [comment]
Hello, thank you for your feedback!
This is a common issue with long-running scripts in Yii. By the way that Yii2 log component is optimized for performance, it doesn't write to log every time that Yii::info is called. It is accumulating the log messages in memory and flushes the logs only when the certain number of logs is reached(1000 by default) or when the script ends, so it is not like the logs will never be written.
It is well documented in [Yii docs](https://www.yiiframework.com/doc/guide/2.0/en/runtime-logging#flushing-exporting), check the link, they also have a possible solution for long running processes.

**Comment by gvanto** [comment]
Ok thanks a lot will check the docs and see if there's a way to make it more realtime-y :-)

**Comment by gvanto** [comment]
Sorry it was working, there was an include missing in (custom db logging class)
