### ISSUE TITLE
Exception 'Error' with message 'Class 'mikemadisonweb\rabbitmq\AbstractConnectionFactory' not found'Exception 'Error' with message 'Class 'mikemadisonweb\rabbitmq\AbstractConnectionFactory' not found'

### ISSUE THREAD

**Issue by kapil-infinity** [mikemadisonweb/yii2-rabbitmq#37]
Hi ,
I am getting the following error while running the consumer on server ubuntu 14, while its working on my local machine which is ubuntu 16.04

in /var/www/html/clm/v1.0/vendor/mikemadisonweb/yii2-rabbitmq/DependencyInjection.php:54

Stack trace:
#0 [internal function]: mikemadisonweb\rabbitmq\DependencyInjection->mikemadisonweb\rabbitmq\{closure}(Object(yii\di\Container), Array, Array)
#1 /var/www/html/clm/v1.0/vendor/yiisoft/yii2/di/Container.php(163): call_user_func(Object(Closure), Object(yii\di\Container), Array, Array)
#2 /var/www/html/clm/v1.0/vendor/mikemadisonweb/yii2-rabbitmq/Configuration.php(155): yii\di\Container->get('rabbit_mq.conne...')
#3 /var/www/html/clm/v1.0/vendor/mikemadisonweb/yii2-rabbitmq/controllers/RabbitMQController.php(205): mikemadisonweb\rabbitmq\Configuration->getConnection('default')
#4 [internal function]: mikemadisonweb\rabbitmq\controllers\RabbitMQController->actionDeleteAll('default')
#5 /var/www/html/clm/v1.0/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#6 /var/www/html/clm/v1.0/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#7 /var/www/html/clm/v1.0/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('delete-all', Array)
#8 /var/www/html/clm/v1.0/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('delete-all', Array)
#9 /var/www/html/clm/v1.0/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('rabbitmq/delete...', Array)
#10 /var/www/html/clm/v1.0/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('rabbitmq/delete...', Array)
#11 /var/www/html/clm/v1.0/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#12 /var/www/html/clm/v1.0/yii(20): yii\base\Application->run()
#13 {main}

**Comment by mikemadisonweb** [comment]
Hello Kapil,
Which version of php are you using? It seems that group use statements are ignored for you.

**Comment by mikemadisonweb** [comment]
Closed due to inactivity.
