### ISSUE TITLE
Issue when starting consumers 

### ISSUE THREAD

**Issue by max-eagleeye** [mikemadisonweb/yii2-rabbitmq#39]
Hi - when starting a consumer up, I get the message "Consumer `Outbound` doesn't exist."

Command: `./yii rabbitmq/consume Outbound`

Config File Snippet for `Consumer`

'consumers' => [
                [
                    'name' => 'Outbound',
                    // Every consumer should define one or more callbacks for corresponding queues
                    'callbacks' => [
                        // queue name => callback class name
                        'Forwarding Outbound' => \components\rabbitmq\OutboundForwarding::class
                    ],
                ],
            ]

**Comment by mikemadisonweb** [comment]
Hi,
Where have you put this config, are you sure that it is being read by Yii?

**Comment by max-eagleeye** [comment]
Hi - i have put it at the same level as producers, etc. It is being read, as an example - when I put in a duplicate consumer with the same name, it complains there are two defined with the same name

**Comment by mikemadisonweb** [comment]
I should be more specific. Is it also in the cli config, for example in the docs I have put it to common.php to ensure it is being read by cli and web versions of the app.
Otherwise, I have no clue what can be the reason of your problem and I need more information.

**Comment by max-eagleeye** [comment]
I've put all the RMQ config in the shared config file, and it seems to pick-up that config when publishing for example. Is there any other info I can provide?

**Comment by mikemadisonweb** [comment]
Try to debug a bit, as the logic is actually very straightforward: 
- Upon reading of the configuration, the consumer is registered as a service in the container with the mentioned name: https://github.com/mikemadisonweb/yii2-rabbitmq/blob/master/DependencyInjection.php#L121
- When you are trying to get the consumer it will check the container by the configured name: https://github.com/mikemadisonweb/yii2-rabbitmq/blob/master/Configuration.php#L175

**Comment by max-eagleeye** [comment]
I'll give it a go moving the config to the console config file. It does try to register, because it throws an exception if you try and register the same name twice

**Comment by max-eagleeye** [comment]
Found the issue - if the callback class isn't defined correctly in the config, it throws the `Consumer doesn't exist error
