### ISSUE TITLE
hello 

### ISSUE THREAD

**Issue by Hkesd** [mikemadisonweb/yii2-rabbitmq#4]
hello, what's your email address? I've got a few questions seeking for your help.
e.g. how to use this extension?

Looking forward to your reply.
Thanks.

**Comment by mikemadisonweb** [comment]
Hello, I have edited my profile, so email is not hidden now. Basic usage example you can find in README file: https://github.com/mikemadisonweb/yii2-rabbitmq/blob/master/README.md
If you have some problems while installing or configuring the extension, please send me an email or open an issue with problem description.
