### ISSUE TITLE
Cant get console logging to work?

### ISSUE THREAD

**Issue by gvanto** [mikemadisonweb/yii2-rabbitmq#43]
I have following but not seeing a "message consumed" output msg on console?

```
'logger' => [
                'log' => true,
                'category' => 'application',
                'print_console' => true,
                'system_memory' => false,
            ],
```

**Comment by mikemadisonweb** [comment]
Hello,
I can not reproduce your issue. It should print to console even by default.
Could you provide more details?
Also, you can check the working example of the extension integration to compare: https://bitbucket.org/MikeMadison/yii2-rabbitmq-test

**Comment by mikemadisonweb** [comment]
Closed due to inactivity.
