### ISSUE TITLE
idle_timeout on consumer should be 0 by default instead of null

### ISSUE THREAD

**Issue by michaelarnauts** [mikemadisonweb/yii2-rabbitmq#46]
Since the upgrade of php-amqplib > 2.9.0, the default config of this package is causing it to loop with 100% CPU.

After a long debugging session, it seems that the default value of `null` of the `idle_timeout` of the Consumer causes this. It should be `0`.

**Comment by mikemadisonweb** [comment]
Thanks! The default value has been changed in the new patch version(2.2.1).
