### ISSUE TITLE
Deleting exchanges not possible

### ISSUE THREAD

**Issue by joorloohuis** [mikemadisonweb/yii2-rabbitmq#49]
Hi Mikhail,

I ran into the situation where I can't delete an exchange on the fly (Exception 'mikemadisonweb\rabbitmq\exceptions\RuntimeException' with message 'Queue xxxx is not configured. Delete is aborted.')
The reason may be clear from the message, Routing::deleteExchange() checks the configured queues in stead of the exchanges.

Joor

**Comment by mikemadisonweb** [comment]
Copy-paste mistake🤦‍♂️ Thanks for notifying, I will fix this in the next minor version.
