### ISSUE TITLE
messagesLimit doesn't work for multiple consumers

### ISSUE THREAD

**Issue by michalsoczynski** [mikemadisonweb/yii2-rabbitmq#5]
Hi @mikemadisonweb ,

I have a problem with multiple consumers. It doesn't work with a flag "messagesLimit", the flag has limit which I set in ConsumerController but I can't set the limit from the command:

It doesn't work:
`php yii rabbitmq-consumer/multiple integration -m=10`

It works:
`php yii rabbitmq-consumer/single integration -m=10`

**Comment by mikemadisonweb** [comment]
Hello, @michalsoczynski 
That seems really odd because it's basically the same console controller. Can you provide some additional information?
What happens with 'multiple' command, it doesn't stop on exceeding message limit? Have you turned on 'print_console' option to control what's happening? Does it throw an error when you paste wrong value, like -m=-1?

**Comment by michalsoczynski** [comment]
Ok I pulled clear version of your repo. I ran for the single consumer with --mesagesLimit=10 and it works, but for the multipleConsumers I used -m instead of --messagesLimit and doesn't work, It was my mistake because I ran different options for each command, sorry for that.

Below you have examples how it works. I can use messagesLimit with double dashes and it works for single and multiple consumers.

```
/app/backend # php yii rabbitmq-consumer/single integration -messagesLimit=-1
It doesn't work beacause I used one dash.
```
```
It works well
/app/backend # php yii rabbitmq-consumer/single integration --messagesLimit=-1
Exception 'InvalidArgumentException' with message 'The -m option should be null or greater than 0'

in /app/backend/vendor/mikemadisonweb/yii2-rabbitmq/controllers/ConsumerController.php:147

Stack trace:
#0 /app/backend/vendor/mikemadisonweb/yii2-rabbitmq/controllers/ConsumerController.php(79): mikemadisonweb\rabbitmq\controllers\ConsumerController->setOptions()
#1 /app/backend/vendor/yiisoft/yii2/base/Controller.php(152): mikemadisonweb\rabbitmq\controllers\ConsumerController->beforeAction(Object(yii\base\InlineAction))
#2 /app/backend/vendor/yiisoft/yii2/console/Controller.php(108): yii\base\Controller->runAction('single', Array)
#3 /app/backend/vendor/yiisoft/yii2/base/Module.php(454): yii\console\Controller->runAction('single', Array)
#4 /app/backend/vendor/yiisoft/yii2/console/Application.php(167): yii\base\Module->runAction('rabbitmq-consum...', Array)
#5 /app/backend/vendor/yiisoft/yii2/console/Application.php(143): yii\console\Application->runAction('rabbitmq-consum...', Array)
#6 /app/backend/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#7 /app/backend/yii(23): yii\base\Application->run()
#8 {main}
```

```
It doesn't work beacause I used one dash.
/app/backend # php yii rabbitmq-consumer/single integration -m=-1
```

```
It doesn't work beacause it doesn't know about alias.
/app/backend # php yii rabbitmq-consumer/single integration --m=-1
Error: Unknown option: --m
```

**Comment by mikemadisonweb** [comment]
Well, yeah, that's how Yii2 handles console [command options](https://nix-tips.ru/yii2-api-guides/guide-en-tutorial-console.html#options). That's also a [common convention](https://en.wikipedia.org/wiki/Command-line_interface#Option_conventions_in_Unix-like_systems) in Unix-systems.
So it's either -m=10 or --messagesLimit=10. Can I close this issue then?

**Comment by michalsoczynski** [comment]
Thank you. Yes, you can close the issue.
