### ISSUE TITLE
Default loger while publishing has not index enable

### ISSUE THREAD

**Issue by DenisOgr** [mikemadisonweb/yii2-rabbitmq#6]
I use follow producer settings:
```
'producers' => [
    'test' => [
        'connection' => 'default',
        'exchange_options' => [
            'name' => 'test',
            'type' => 'direct',
            'declare' => true,
        ],
    ],
],
```

and I dont want use logger.
But I get error `'Undefined index: enable'`

I explain this library and I found this code 
```
if ($this->logger['enable']) {
.....
}
``` 
in  `vendor/mikemadisonweb/yii2-rabbitmq/components/Producer.php:73`
but in this place `$this->logger` is equal null.

PS: also I found this code:
```
 $this->logger = array_replace($this->getDefaultLoggerOptions(), $this->logger);
```
in vendor/mikemadisonweb/yii2-rabbitmq/Configuration.php:143 (in method loadConsumers)

Why you didnt use `getDefaultLoggerOptions` in method loadProducers ?
How to fix it?

**Comment by mikemadisonweb** [comment]
Hi Denis,
Logger defaults setter has been added to Producer invocation as well: https://github.com/mikemadisonweb/yii2-rabbitmq/blob/master/Configuration.php#L82
Thank you for contribution.
To fix your error, please update package to the latest version (1.5.1 currently) and you should be fine. Also, be advised that in new version queue and exchange default options was changed. There is a new section in README file about that: https://github.com/mikemadisonweb/yii2-rabbitmq#defaults
